from typing import Callable, Iterable, overload, TypeVar
T = TypeVar('T')

@overload
def njit(cache: bool = False, parallel: bool = False, nogil: bool = False, fastmath: bool = False) -> Callable[[T], T]: ...
@overload
def njit(f: T, cache: bool = False, parallel: bool = False, nogil: bool = False, fastmath: bool = False) -> T: ...

def prange(num: int) -> Iterable[int]: ...
