name: Tag

on:
  workflow_run:
    workflows: ['Test']
    branches: [main]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Install dependencies
      run: |
        uv venv
        uv pip compile --extra=dev pyproject.toml -o requirements.txt
        uv pip sync requirements.txt

    - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: uv run ./scripts/publish.sh

    - name: Tag
      run: |
        git push
        git push --tags
